name: marketrec
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pillow
  - pandas
  - opencv
  - sqlalchemy
  - scipy
  - streamlit
  - pip:
    - tensorflow==2.20.0
    - fastapi==0.95.2
    - "uvicorn[standard]==0.22.0"
    - python-multipart==0.0.6
    - requests==2.31.0
